let generalKnowledgeQuestions = [
    [
      "What is the capital of Australia?",
      "Sydney",
      "Melbourne",
      "Canberra",
      "Perth",
      2,
    ],
    [
      "Who painted the famous artwork 'The Starry Night'?",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Claude Monet",
      1,
    ],
    ["What is the currency of Japan?", "Yen", "Won", "Dollar", "Euro", 0],
    [
      "In which year did the Berlin Wall fall?",
      "1989",
      "1991",
      "1987",
      "1993",
      0,
    ],
    [
      "Which philosopher wrote the book 'Thus Spoke Zarathustra'?",
      "Friedrich Nietzsche",
      "Socrates",
      "Plato",
      "Aristotle",
      0,
    ],
    [
      "What is the chemical formula for caffeine?",
      "C8H10N4O2",
      "H2O",
      "NaCl",
      "CO2",
      0,
    ],
    [
      "What is the largest planet in our solar system?",
      "Mars",
      "Jupiter",
      "Venus",
      "Saturn",
      1,
    ],
    [
      "What is the symbol for the chemical element 'Oxygen'?",
      "O",
      "C",
      "H",
      "N",
      0,
    ],
    [
      "Who developed the theory of general relativity?",
      "Isaac Newton",
      "Stephen Hawking",
      "Albert Einstein",
      "Galileo Galilei",
      2,
    ],
    [
      "What is the process of converting a solid directly into a gas called?",
      "Melting",
      "Freezing",
      "Condensation",
      "Sublimation",
      3,
    ],
    [
      "What is the smallest unit of matter?",
      "Atom",
      "Molecule",
      "Cell",
      "Electron",
      0,
    ],
    [
      "What is the study of fossils called?",
      "Paleontology",
      "Geology",
      "Biology",
      "Anthropology",
      0,
    ],
    ["What is the capital of France?", "Paris", "London", "Berlin", "Madrid", 0],
    [
      "Who wrote the novel 'To Kill a Mockingbird'?",
      "Harper Lee",
      "J.D. Salinger",
      "Mark Twain",
      "Charles Dickens",
      0,
    ],
    ["How many sides does a hexagon have?", "4", "6", "8", "10", 1],
    [
      "What is the capital of China?",
      "Beijing",
      "Shanghai",
      "Hong Kong",
      "Tokyo",
      0,
    ],
    [
      "Who is the author of the famous novel '1984'?",
      "George Orwell",
      "F. Scott Fitzgerald",
      "Herman Melville",
      "J.R.R. Tolkien",
      0,
    ],
    [
      "Which country is known as the 'Land of the Midnight Sun'?",
      "Norway",
      "Sweden",
      "Finland",
      "Iceland",
      0,
    ],
    [
      "What is the largest desert in the world?",
      "Sahara Desert",
      "Gobi Desert",
      "Arabian Desert",
      "Kalahari Desert",
      0,
    ],
    [
      "Who discovered penicillin?",
      "Alexander Fleming",
      "Louis Pasteur",
      "Marie Curie",
      "Thomas Edison",
      0,
    ],
    [
      "What is the national animal of Canada?",
      "Lion",
      "Bald Eagle",
      "Panda",
      "Beaver",
      3,
    ],
    [
      "Which planet is known as the 'Blue Planet'?",
      "Mars",
      "Venus",
      "Earth",
      "Neptune",
      2,
    ],
    ["What is the chemical symbol for silver?", "Au", "Ag", "Fe", "Pb", 1],
    [
      "Who invented the light bulb?",
      "Thomas Edison",
      "Benjamin Franklin",
      "Nikola Tesla",
      "Isaac Newton",
      0,
    ],
    [
      "What is the largest waterfall in the world?",
      "Angel Falls",
      "Victoria Falls",
      "Niagara Falls",
      "Iguazu Falls",
      1,
    ],
    [
      "What is the capital of Brazil?",
      "Rio de Janeiro",
      "Sao Paulo",
      "Brasilia",
      "Buenos Aires",
      2,
    ],
    [
      "Which city serves as the capital of South Africa?",
      "Johannesburg",
      "Cape Town",
      "Pretoria",
      "Nairobi",
      2,
    ],
    [
      "What is the capital of Thailand?",
      "Bangkok",
      "Phuket",
      "Chiang Mai",
      "Ho Chi Minh City",
      0,
    ],
    [
      "Which city is the capital of Canada?",
      "Toronto",
      "Montreal",
      "Vancouver",
      "Ottawa",
      3,
    ],
    [
      "What is the capital of Saudi Arabia?",
      "Dubai",
      "Riyadh",
      "Mecca",
      "Doha",
      1,
    ],
    [
      "Which city serves as the capital of Argentina?",
      "Buenos Aires",
      "Santiago",
      "Lima",
      "Bogota",
      0,
    ],
    [
      "What is the capital of Sweden?",
      "Stockholm",
      "Copenhagen",
      "Oslo",
      "Helsinki",
      0,
    ],
    [
      "Which city is the capital of Turkey?",
      "Istanbul",
      "Ankara",
      "Athens",
      "Rome",
      1,
    ],
    [
      "What is the capital of South Korea?",
      "Tokyo",
      "Beijing",
      "Seoul",
      "Pyongyang",
      2,
    ],
    [
      "Which city serves as the capital of Australia?",
      "Sydney",
      "Melbourne",
      "Canberra",
      "Perth",
      2,
    ],
  ];