let generalKnowledgeQuestions = [
    [
      "What is the capital of Australia?",
      "Sydney",
      "Melbourne",
      "Canberra",
      "Perth",
      2,
    ],
    [
      "Who painted the famous artwork 'The Starry Night'?",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Claude Monet",
      1,
    ],
    ["What is the currency of Japan?", "Yen", "Won", "Dollar", "Euro", 0],
    [
      "In which year did the Berlin Wall fall?",
      "1989",
      "1991",
      "1987",
      "1993",
      0,
    ],
    [
      "Which philosopher wrote the book 'Thus Spoke Zarathustra'?",
      "Friedrich Nietzsche",
      "Socrates",
      "Plato",
      "Aristotle",
      0,
    ],
    [
      "What is the chemical formula for caffeine?",
      "C8H10N4O2",
      "H2O",
      "NaCl",
      "CO2",
      0,
    ],
    [
      "What is the largest planet in our solar system?",
      "Mars",
      "Jupiter",
      "Venus",
      "Saturn",
      1,
    ],
    [
      "What is the symbol for the chemical element 'Oxygen'?",
      "O",
      "C",
      "H",
      "N",
      0,
    ],
    [
      "Who developed the theory of general relativity?",
      "Isaac Newton",
      "Stephen Hawking",
      "Albert Einstein",
      "Galileo Galilei",
      2,
    ],
    [
      "What is the process of converting a solid directly into a gas called?",
      "Melting",
      "Freezing",
      "Condensation",
      "Sublimation",
      3,
    ],
    [
      "What is the smallest unit of matter?",
      "Atom",
      "Molecule",
      "Cell",
      "Electron",
      0,
    ],
    [
      "What is the study of fossils called?",
      "Paleontology",
      "Geology",
      "Biology",
      "Anthropology",
      0,
    ],
    ["What is the capital of France?", "Paris", "London", "Berlin", "Madrid", 0],
    [
      "Who wrote the novel 'To Kill a Mockingbird'?",
      "Harper Lee",
      "J.D. Salinger",
      "Mark Twain",
      "Charles Dickens",
      0,
    ],
    ["How many sides does a hexagon have?", "4", "6", "8", "10", 1],
    [
      "What is the capital of China?",
      "Beijing",
      "Shanghai",
      "Hong Kong",
      "Tokyo",
      0,
    ],
    [
      "Who is the author of the famous novel '1984'?",
      "George Orwell",
      "F. Scott Fitzgerald",
      "Herman Melville",
      "J.R.R. Tolkien",
      0,
    ],
    [
      "Which country is known as the 'Land of the Midnight Sun'?",
      "Norway",
      "Sweden",
      "Finland",
      "Iceland",
      0,
    ],
    [
      "What is the largest desert in the world?",
      "Sahara Desert",
      "Gobi Desert",
      "Arabian Desert",
      "Kalahari Desert",
      0,
    ],
    [
      "Who discovered penicillin?",
      "Alexander Fleming",
      "Louis Pasteur",
      "Marie Curie",
      "Thomas Edison",
      0,
    ],
    [
      "What is the national animal of Canada?",
      "Lion",
      "Bald Eagle",
      "Panda",
      "Beaver",
      3,
    ],
    [
      "Which planet is known as the 'Blue Planet'?",
      "Mars",
      "Venus",
      "Earth",
      "Neptune",
      2,
    ],
    ["What is the chemical symbol for silver?", "Au", "Ag", "Fe", "Pb", 1],
    [
      "Who invented the light bulb?",
      "Thomas Edison",
      "Benjamin Franklin",
      "Nikola Tesla",
      "Isaac Newton",
      0,
    ],
    [
      "What is the largest waterfall in the world?",
      "Angel Falls",
      "Victoria Falls",
      "Niagara Falls",
      "Iguazu Falls",
      1,
    ],
    [
      "What is the capital of Brazil?",
      "Rio de Janeiro",
      "Sao Paulo",
      "Brasilia",
      "Buenos Aires",
      2,
    ],
    [
      "Which city serves as the capital of South Africa?",
      "Johannesburg",
      "Cape Town",
      "Pretoria",
      "Nairobi",
      2,
    ],
    [
      "What is the capital of Thailand?",
      "Bangkok",
      "Phuket",
      "Chiang Mai",
      "Ho Chi Minh City",
      0,
    ],
    [
      "Which city is the capital of Canada?",
      "Toronto",
      "Montreal",
      "Vancouver",
      "Ottawa",
      3,
    ],
    [
      "What is the capital of Saudi Arabia?",
      "Dubai",
      "Riyadh",
      "Mecca",
      "Doha",
      1,
    ],
    [
      "Which city serves as the capital of Argentina?",
      "Buenos Aires",
      "Santiago",
      "Lima",
      "Bogota",
      0,
    ],
    [
      "What is the capital of Sweden?",
      "Stockholm",
      "Copenhagen",
      "Oslo",
      "Helsinki",
      0,
    ],
    [
      "Which city is the capital of Turkey?",
      "Istanbul",
      "Ankara",
      "Athens",
      "Rome",
      1,
    ],
    [
      "What is the capital of South Korea?",
      "Tokyo",
      "Beijing",
      "Seoul",
      "Pyongyang",
      2,
    ],
    [
      "Which city serves as the capital of Australia?",
      "Sydney",
      "Melbourne",
      "Canberra",
      "Perth",
      2,
    ],
  ];

  let historyQuestions = [
    ["Which year did World War I begin?", "1914", "1915", "1916", "1917", 0],
    [
      "Who was the first President of the United States?",
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John Adams",
      0,
    ],
    [
      "Which city was the capital of the Aztec empire?",
      "Tenochtitlan",
      "Cusco",
      "Machu Picchu",
      "Teotihuacan",
      0,
    ],
    [
      "Who painted the ceiling of the Sistine Chapel?",
      "Michelangelo",
      "Leonardo da Vinci",
      "Raphael",
      "Donatello",
      0,
    ],
    [
      "In which year did the Industrial Revolution begin?",
      "1750",
      "1800",
      "1850",
      "1900",
      0,
    ],
    [
      "Who wrote the play 'Romeo and Juliet'?",
      "William Shakespeare",
      "Christopher Marlowe",
      "George Bernard Shaw",
      "Oscar Wilde",
      0,
    ],
    [
      "Which country was the first to circumnavigate the globe?",
      "Portugal",
      "Spain",
      "England",
      "France",
      1,
    ],
    [
      "Who was the last pharaoh of ancient Egypt?",
      "Cleopatra",
      "Nefertiti",
      "Hatshepsut",
      "Tutankhamun",
      0,
    ],
    [
      "In which year did the American Civil War end?",
      "1865",
      "1870",
      "1863",
      "1867",
      0,
    ],
    [
      "Which European explorer reached India by sea in 1498?",
      "Christopher Columbus",
      "Vasco da Gama",
      "Ferdinand Magellan",
      "James Cook",
      1,
    ],
    [
      "Who was the first female Prime Minister of the United Kingdom?",
      "Margaret Thatcher",
      "Angela Merkel",
      "Theresa May",
      "Indira Gandhi",
      0,
    ],
    [
      "In which year did the French Revolution begin?",
      "1789",
      "1800",
      "1750",
      "1820",
      0,
    ],
    [
      "Who is credited with the invention of the printing press?",
      "Johannes Gutenberg",
      "Leonardo da Vinci",
      "Isaac Newton",
      "Galileo Galilei",
      0,
    ],
    [
      "Which city was the capital of the Roman Empire?",
      "Rome",
      "Athens",
      "Alexandria",
      "Constantinople",
      3,
    ],
    [
      "Who delivered the famous 'I Have a Dream' speech?",
      "Martin Luther King Jr.",
      "Nelson Mandela",
      "Barack Obama",
      "Malcolm X",
      0,
    ],
    ["Which year did World War I begin?", "1914", "1915", "1916", "1917", 0],
    [
      "Who was the first President of the United States?",
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John F. Kennedy",
      0,
    ],
    [
      "Which country was ruled by Adolf Hitler during World War II?",
      "France",
      "Germany",
      "Russia",
      "Italy",
      1,
    ],
    ["When did the American Civil War end?", "1863", "1864", "1865", "1866", 2],
    [
      "Who was the leader of the Soviet Union during World War II?",
      "Joseph Stalin",
      "Vladimir Lenin",
      "Mikhail Gorbachev",
      "Nikita Khrushchev",
      0,
    ],
    [
      "Which city was the capital of the Byzantine Empire?",
      "Athens",
      "Rome",
      "Constantinople",
      "Alexandria",
      2,
    ],
    [
      "When did the Industrial Revolution take place?",
      "16th century",
      "17th century",
      "18th century",
      "19th century",
      2,
    ],
    [
      "Who wrote the book 'The Communist Manifesto'?",
      "Karl Marx",
      "Adam Smith",
      "John Locke",
      "Thomas Hobbes",
      0,
    ],
    [
      "Which country colonized India?",
      "France",
      "Spain",
      "Portugal",
      "United Kingdom",
      3,
    ],
    [
      "Who was the last Queen of France before the French Revolution?",
      "Catherine the Great",
      "Marie Antoinette",
      "Queen Victoria",
      "Elizabeth I",
      1,
    ],
    [
      "When did the Renaissance period occur?",
      "14th century",
      "15th century",
      "16th century",
      "17th century",
      2,
    ],
    [
      "Which war was fought between North and South Korea from 1950 to 1953?",
      "World War I",
      "Vietnam War",
      "Korean War",
      "Cold War",
      2,
    ],
    [
      "Who discovered America?",
      "Christopher Columbus",
      "Amerigo Vespucci",
      "Vasco da Gama",
      "Ferdinand Magellan",
      0,
    ],
    [
      "Which civilization built the Great Wall of China?",
      "Mayans",
      "Aztecs",
      "Incas",
      "Chinese",
      3,
    ],
    [
      "Who was the first Emperor of Rome?",
      "Julius Caesar",
      "Augustus",
      "Nero",
      "Constantine",
      1,
    ],
    ["When did the French Revolution begin?", "1787", "1788", "1789", "1790", 2],
    [
      "Which country was Nelson Mandela the President of?",
      "South Africa",
      "Kenya",
      "Nigeria",
      "Egypt",
      0,
    ],
    ["When was the Magna Carta signed?", "1210", "1215", "1220", "1225", 1],
    [
      "Who was the first female Prime Minister of the United Kingdom?",
      "Margaret Thatcher",
      "Angela Merkel",
      "Theresa May",
      "Jacinda Ardern",
      0,
    ],
    [
      "Which country was Napoleon Bonaparte born in?",
      "France",
      "Italy",
      "Germany",
      "Spain",
      1,
    ],
    [
      "When was the Declaration of Independence signed?",
      "1774",
      "1775",
      "1776",
      "1777",
      2,
    ],
    [
      "Who led the Bolshevik Revolution in Russia in 1917?",
      "Vladimir Lenin",
      "Leon Trotsky",
      "Joseph Stalin",
      "Mikhail Gorbachev",
      0,
    ],
    [
      "Which ancient civilization built the city of Machu Picchu?",
      "Mayans",
      "Aztecs",
      "Incas",
      "Romans",
      2,
    ],
    ["When was the Berlin Wall demolished?", "1985", "1987", "1989", "1991", 2],
    [
      "Who was the first President of the Russian Federation?",
      "Vladimir Putin",
      "Boris Yeltsin",
      "Mikhail Gorbachev",
      "Dmitry Medvedev",
      1,
    ],
    [
      "Which ancient civilization built the pyramids of Egypt?",
      "Greeks",
      "Persians",
      "Egyptians",
      "Babylonians",
      2,
    ],
    [
      "When was the Battle of Waterloo fought?",
      "1804",
      "1810",
      "1815",
      "1820",
      2,
    ],
    [
      "Who was the first President of the United States of America?",
      "John Adams",
      "Thomas Jefferson",
      "George Washington",
      "James Madison",
      2,
    ],
    [
      "Which country was once ruled by the great warrior Genghis Khan?",
      "Mongolia",
      "China",
      "India",
      "Russia",
      0,
    ],
    [
      "When did the Russian Revolution take place?",
      "1905",
      "1910",
      "1917",
      "1922",
      2,
    ],
    [
      "Who was the first African-American President of the United States?",
      "Barack Obama",
      "Joe Biden",
      "Bill Clinton",
      "George W. Bush",
      0,
    ],
    [
      "Who led the Salt March (Dandi March) in India as part of the Civil Disobedience Movement?",
      "Jawaharlal Nehru",
      "Mahatma Gandhi",
      "Subhash Chandra Bose",
      "Bhagat Singh",
      1,
    ],
    [
      "In which year did India gain independence from British rule?",
      "1945",
      "1947",
      "1950",
      "1962",
      1,
    ],
    [
      "Who is known as the 'Father of the Indian Constitution'?",
      "Mahatma Gandhi",
      "Jawaharlal Nehru",
      "B.R. Ambedkar",
      "Sardar Vallabhbhai Patel",
      2,
    ],
    [
      "Which event marked the formal beginning of the Indian National Movement?",
      "Revolt of 1857",
      "Partition of Bengal in 1905",
      "Formation of Indian National Congress in 1885",
      "Quit India Movement in 1942",
      2,
    ],
    [
      "Who was the first Prime Minister of India?",
      "Jawaharlal Nehru",
      "Indira Gandhi",
      "Rajiv Gandhi",
      "Morarji Desai",
      0,
    ],
    [
      "Who was the last Viceroy of India?",
      "Lord Mountbatten",
      "Lord Curzon",
      "Lord Dalhousie",
      "Lord Canning",
      0,
    ],
    [
      "Which Indian king is known as the 'Lion of Punjab'?",
      "Raja Raja Chola",
      "Shivaji",
      "Akbar",
      "Maharaja Ranjit Singh",
      3,
    ],
    [
      "Who was the leader of the Indian National Army (Azad Hind Fauj) during World War II?",
      "Subhash Chandra Bose",
      "Jawaharlal Nehru",
      "Sardar Vallabhbhai Patel",
      "Bhagat Singh",
      0,
    ],
    [
      "Who was the first Indian woman to become the President of the Indian National Congress?",
      "Indira Gandhi",
      "Sarojini Naidu",
      "Vijaya Lakshmi Pandit",
      "Annie Besant",
      1,
    ],
    [
      "Who is known as the 'Iron Man of India'?",
      "Jawaharlal Nehru",
      "Sardar Vallabhbhai Patel",
      "Subhash Chandra Bose",
      "Lal Bahadur Shastri",
      1,
    ],
    [
      "Which Indian state was the first to achieve full statehood?",
      "Maharashtra",
      "Kerala",
      "Tamil Nadu",
      "Andhra Pradesh",
      3,
    ],
    [
      "Who composed the music for the Indian National Anthem?",
      "Rabindranath Tagore",
      "Bhimsen Joshi",
      "A.R. Rahman",
      "M.S. Subbulakshmi",
      0,
    ],
    [
      "Which Indian city served as the capital of British India from 1911 to 1947?",
      "Kolkata",
      "Mumbai",
      "Chennai",
      "Delhi",
      3,
    ],
    [
      "Who was the first Indian to win the Nobel Prize?",
      "Rabindranath Tagore",
      "C.V. Raman",
      "Hargobind Khorana",
      "Amartya Sen",
      0,
    ],
    [
      "Who is known as the 'Nightingle of India'?",
      "Lata Mangeshkar",
      "Asha Bhosle",
      "Sarojini Naidu",
      "M.S. Subbulakshmi",
      2,
    ],
  ];