let generalKnowledgeQuestions = [
    [
      "What is the capital of Australia?",
      "Sydney",
      "Melbourne",
      "Canberra",
      "Perth",
      2,
    ],
    [
      "Who painted the famous artwork 'The Starry Night'?",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Leonardo da Vinci",
      "Claude Monet",
      1,
    ],
    ["What is the currency of Japan?", "Yen", "Won", "Dollar", "Euro", 0],
    [
      "In which year did the Berlin Wall fall?",
      "1989",
      "1991",
      "1987",
      "1993",
      0,
    ],
    [
      "Which philosopher wrote the book 'Thus Spoke Zarathustra'?",
      "Friedrich Nietzsche",
      "Socrates",
      "Plato",
      "Aristotle",
      0,
    ],
    [
      "What is the chemical formula for caffeine?",
      "C8H10N4O2",
      "H2O",
      "NaCl",
      "CO2",
      0,
    ],
    [
      "What is the largest planet in our solar system?",
      "Mars",
      "Jupiter",
      "Venus",
      "Saturn",
      1,
    ],
    [
      "What is the symbol for the chemical element 'Oxygen'?",
      "O",
      "C",
      "H",
      "N",
      0,
    ],
    [
      "Who developed the theory of general relativity?",
      "Isaac Newton",
      "Stephen Hawking",
      "Albert Einstein",
      "Galileo Galilei",
      2,
    ],
    [
      "What is the process of converting a solid directly into a gas called?",
      "Melting",
      "Freezing",
      "Condensation",
      "Sublimation",
      3,
    ],
    [
      "What is the smallest unit of matter?",
      "Atom",
      "Molecule",
      "Cell",
      "Electron",
      0,
    ],
    [
      "What is the study of fossils called?",
      "Paleontology",
      "Geology",
      "Biology",
      "Anthropology",
      0,
    ],
    ["What is the capital of France?", "Paris", "London", "Berlin", "Madrid", 0],
    [
      "Who wrote the novel 'To Kill a Mockingbird'?",
      "Harper Lee",
      "J.D. Salinger",
      "Mark Twain",
      "Charles Dickens",
      0,
    ],
    ["How many sides does a hexagon have?", "4", "6", "8", "10", 1],
    [
      "What is the capital of China?",
      "Beijing",
      "Shanghai",
      "Hong Kong",
      "Tokyo",
      0,
    ],
    [
      "Who is the author of the famous novel '1984'?",
      "George Orwell",
      "F. Scott Fitzgerald",
      "Herman Melville",
      "J.R.R. Tolkien",
      0,
    ],
    [
      "Which country is known as the 'Land of the Midnight Sun'?",
      "Norway",
      "Sweden",
      "Finland",
      "Iceland",
      0,
    ],
    [
      "What is the largest desert in the world?",
      "Sahara Desert",
      "Gobi Desert",
      "Arabian Desert",
      "Kalahari Desert",
      0,
    ],
    [
      "Who discovered penicillin?",
      "Alexander Fleming",
      "Louis Pasteur",
      "Marie Curie",
      "Thomas Edison",
      0,
    ],
    [
      "What is the national animal of Canada?",
      "Lion",
      "Bald Eagle",
      "Panda",
      "Beaver",
      3,
    ],
    [
      "Which planet is known as the 'Blue Planet'?",
      "Mars",
      "Venus",
      "Earth",
      "Neptune",
      2,
    ],
    ["What is the chemical symbol for silver?", "Au", "Ag", "Fe", "Pb", 1],
    [
      "Who invented the light bulb?",
      "Thomas Edison",
      "Benjamin Franklin",
      "Nikola Tesla",
      "Isaac Newton",
      0,
    ],
    [
      "What is the largest waterfall in the world?",
      "Angel Falls",
      "Victoria Falls",
      "Niagara Falls",
      "Iguazu Falls",
      1,
    ],
    [
      "What is the capital of Brazil?",
      "Rio de Janeiro",
      "Sao Paulo",
      "Brasilia",
      "Buenos Aires",
      2,
    ],
    [
      "Which city serves as the capital of South Africa?",
      "Johannesburg",
      "Cape Town",
      "Pretoria",
      "Nairobi",
      2,
    ],
    [
      "What is the capital of Thailand?",
      "Bangkok",
      "Phuket",
      "Chiang Mai",
      "Ho Chi Minh City",
      0,
    ],
    [
      "Which city is the capital of Canada?",
      "Toronto",
      "Montreal",
      "Vancouver",
      "Ottawa",
      3,
    ],
    [
      "What is the capital of Saudi Arabia?",
      "Dubai",
      "Riyadh",
      "Mecca",
      "Doha",
      1,
    ],
    [
      "Which city serves as the capital of Argentina?",
      "Buenos Aires",
      "Santiago",
      "Lima",
      "Bogota",
      0,
    ],
    [
      "What is the capital of Sweden?",
      "Stockholm",
      "Copenhagen",
      "Oslo",
      "Helsinki",
      0,
    ],
    [
      "Which city is the capital of Turkey?",
      "Istanbul",
      "Ankara",
      "Athens",
      "Rome",
      1,
    ],
    [
      "What is the capital of South Korea?",
      "Tokyo",
      "Beijing",
      "Seoul",
      "Pyongyang",
      2,
    ],
    [
      "Which city serves as the capital of Australia?",
      "Sydney",
      "Melbourne",
      "Canberra",
      "Perth",
      2,
    ],
  ];

  let historyQuestions = [
    ["Which year did World War I begin?", "1914", "1915", "1916", "1917", 0],
    [
      "Who was the first President of the United States?",
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John Adams",
      0,
    ],
    [
      "Which city was the capital of the Aztec empire?",
      "Tenochtitlan",
      "Cusco",
      "Machu Picchu",
      "Teotihuacan",
      0,
    ],
    [
      "Who painted the ceiling of the Sistine Chapel?",
      "Michelangelo",
      "Leonardo da Vinci",
      "Raphael",
      "Donatello",
      0,
    ],
    [
      "In which year did the Industrial Revolution begin?",
      "1750",
      "1800",
      "1850",
      "1900",
      0,
    ],
    [
      "Who wrote the play 'Romeo and Juliet'?",
      "William Shakespeare",
      "Christopher Marlowe",
      "George Bernard Shaw",
      "Oscar Wilde",
      0,
    ],
    [
      "Which country was the first to circumnavigate the globe?",
      "Portugal",
      "Spain",
      "England",
      "France",
      1,
    ],
    [
      "Who was the last pharaoh of ancient Egypt?",
      "Cleopatra",
      "Nefertiti",
      "Hatshepsut",
      "Tutankhamun",
      0,
    ],
    [
      "In which year did the American Civil War end?",
      "1865",
      "1870",
      "1863",
      "1867",
      0,
    ],
    [
      "Which European explorer reached India by sea in 1498?",
      "Christopher Columbus",
      "Vasco da Gama",
      "Ferdinand Magellan",
      "James Cook",
      1,
    ],
    [
      "Who was the first female Prime Minister of the United Kingdom?",
      "Margaret Thatcher",
      "Angela Merkel",
      "Theresa May",
      "Indira Gandhi",
      0,
    ],
    [
      "In which year did the French Revolution begin?",
      "1789",
      "1800",
      "1750",
      "1820",
      0,
    ],
    [
      "Who is credited with the invention of the printing press?",
      "Johannes Gutenberg",
      "Leonardo da Vinci",
      "Isaac Newton",
      "Galileo Galilei",
      0,
    ],
    [
      "Which city was the capital of the Roman Empire?",
      "Rome",
      "Athens",
      "Alexandria",
      "Constantinople",
      3,
    ],
    [
      "Who delivered the famous 'I Have a Dream' speech?",
      "Martin Luther King Jr.",
      "Nelson Mandela",
      "Barack Obama",
      "Malcolm X",
      0,
    ],
    ["Which year did World War I begin?", "1914", "1915", "1916", "1917", 0],
    [
      "Who was the first President of the United States?",
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John F. Kennedy",
      0,
    ],
    [
      "Which country was ruled by Adolf Hitler during World War II?",
      "France",
      "Germany",
      "Russia",
      "Italy",
      1,
    ],
    ["When did the American Civil War end?", "1863", "1864", "1865", "1866", 2],
    [
      "Who was the leader of the Soviet Union during World War II?",
      "Joseph Stalin",
      "Vladimir Lenin",
      "Mikhail Gorbachev",
      "Nikita Khrushchev",
      0,
    ],
    [
      "Which city was the capital of the Byzantine Empire?",
      "Athens",
      "Rome",
      "Constantinople",
      "Alexandria",
      2,
    ],
    [
      "When did the Industrial Revolution take place?",
      "16th century",
      "17th century",
      "18th century",
      "19th century",
      2,
    ],
    [
      "Who wrote the book 'The Communist Manifesto'?",
      "Karl Marx",
      "Adam Smith",
      "John Locke",
      "Thomas Hobbes",
      0,
    ],
    [
      "Which country colonized India?",
      "France",
      "Spain",
      "Portugal",
      "United Kingdom",
      3,
    ],
    [
      "Who was the last Queen of France before the French Revolution?",
      "Catherine the Great",
      "Marie Antoinette",
      "Queen Victoria",
      "Elizabeth I",
      1,
    ],
    [
      "When did the Renaissance period occur?",
      "14th century",
      "15th century",
      "16th century",
      "17th century",
      2,
    ],
    [
      "Which war was fought between North and South Korea from 1950 to 1953?",
      "World War I",
      "Vietnam War",
      "Korean War",
      "Cold War",
      2,
    ],
    [
      "Who discovered America?",
      "Christopher Columbus",
      "Amerigo Vespucci",
      "Vasco da Gama",
      "Ferdinand Magellan",
      0,
    ],
    [
      "Which civilization built the Great Wall of China?",
      "Mayans",
      "Aztecs",
      "Incas",
      "Chinese",
      3,
    ],
    [
      "Who was the first Emperor of Rome?",
      "Julius Caesar",
      "Augustus",
      "Nero",
      "Constantine",
      1,
    ],
    ["When did the French Revolution begin?", "1787", "1788", "1789", "1790", 2],
    [
      "Which country was Nelson Mandela the President of?",
      "South Africa",
      "Kenya",
      "Nigeria",
      "Egypt",
      0,
    ],
    ["When was the Magna Carta signed?", "1210", "1215", "1220", "1225", 1],
    [
      "Who was the first female Prime Minister of the United Kingdom?",
      "Margaret Thatcher",
      "Angela Merkel",
      "Theresa May",
      "Jacinda Ardern",
      0,
    ],
    [
      "Which country was Napoleon Bonaparte born in?",
      "France",
      "Italy",
      "Germany",
      "Spain",
      1,
    ],
    [
      "When was the Declaration of Independence signed?",
      "1774",
      "1775",
      "1776",
      "1777",
      2,
    ],
    [
      "Who led the Bolshevik Revolution in Russia in 1917?",
      "Vladimir Lenin",
      "Leon Trotsky",
      "Joseph Stalin",
      "Mikhail Gorbachev",
      0,
    ],
    [
      "Which ancient civilization built the city of Machu Picchu?",
      "Mayans",
      "Aztecs",
      "Incas",
      "Romans",
      2,
    ],
    ["When was the Berlin Wall demolished?", "1985", "1987", "1989", "1991", 2],
    [
      "Who was the first President of the Russian Federation?",
      "Vladimir Putin",
      "Boris Yeltsin",
      "Mikhail Gorbachev",
      "Dmitry Medvedev",
      1,
    ],
    [
      "Which ancient civilization built the pyramids of Egypt?",
      "Greeks",
      "Persians",
      "Egyptians",
      "Babylonians",
      2,
    ],
    [
      "When was the Battle of Waterloo fought?",
      "1804",
      "1810",
      "1815",
      "1820",
      2,
    ],
    [
      "Who was the first President of the United States of America?",
      "John Adams",
      "Thomas Jefferson",
      "George Washington",
      "James Madison",
      2,
    ],
    [
      "Which country was once ruled by the great warrior Genghis Khan?",
      "Mongolia",
      "China",
      "India",
      "Russia",
      0,
    ],
    [
      "When did the Russian Revolution take place?",
      "1905",
      "1910",
      "1917",
      "1922",
      2,
    ],
    [
      "Who was the first African-American President of the United States?",
      "Barack Obama",
      "Joe Biden",
      "Bill Clinton",
      "George W. Bush",
      0,
    ],
    [
      "Who led the Salt March (Dandi March) in India as part of the Civil Disobedience Movement?",
      "Jawaharlal Nehru",
      "Mahatma Gandhi",
      "Subhash Chandra Bose",
      "Bhagat Singh",
      1,
    ],
    [
      "In which year did India gain independence from British rule?",
      "1945",
      "1947",
      "1950",
      "1962",
      1,
    ],
    [
      "Who is known as the 'Father of the Indian Constitution'?",
      "Mahatma Gandhi",
      "Jawaharlal Nehru",
      "B.R. Ambedkar",
      "Sardar Vallabhbhai Patel",
      2,
    ],
    [
      "Which event marked the formal beginning of the Indian National Movement?",
      "Revolt of 1857",
      "Partition of Bengal in 1905",
      "Formation of Indian National Congress in 1885",
      "Quit India Movement in 1942",
      2,
    ],
    [
      "Who was the first Prime Minister of India?",
      "Jawaharlal Nehru",
      "Indira Gandhi",
      "Rajiv Gandhi",
      "Morarji Desai",
      0,
    ],
    [
      "Who was the last Viceroy of India?",
      "Lord Mountbatten",
      "Lord Curzon",
      "Lord Dalhousie",
      "Lord Canning",
      0,
    ],
    [
      "Which Indian king is known as the 'Lion of Punjab'?",
      "Raja Raja Chola",
      "Shivaji",
      "Akbar",
      "Maharaja Ranjit Singh",
      3,
    ],
    [
      "Who was the leader of the Indian National Army (Azad Hind Fauj) during World War II?",
      "Subhash Chandra Bose",
      "Jawaharlal Nehru",
      "Sardar Vallabhbhai Patel",
      "Bhagat Singh",
      0,
    ],
    [
      "Who was the first Indian woman to become the President of the Indian National Congress?",
      "Indira Gandhi",
      "Sarojini Naidu",
      "Vijaya Lakshmi Pandit",
      "Annie Besant",
      1,
    ],
    [
      "Who is known as the 'Iron Man of India'?",
      "Jawaharlal Nehru",
      "Sardar Vallabhbhai Patel",
      "Subhash Chandra Bose",
      "Lal Bahadur Shastri",
      1,
    ],
    [
      "Which Indian state was the first to achieve full statehood?",
      "Maharashtra",
      "Kerala",
      "Tamil Nadu",
      "Andhra Pradesh",
      3,
    ],
    [
      "Who composed the music for the Indian National Anthem?",
      "Rabindranath Tagore",
      "Bhimsen Joshi",
      "A.R. Rahman",
      "M.S. Subbulakshmi",
      0,
    ],
    [
      "Which Indian city served as the capital of British India from 1911 to 1947?",
      "Kolkata",
      "Mumbai",
      "Chennai",
      "Delhi",
      3,
    ],
    [
      "Who was the first Indian to win the Nobel Prize?",
      "Rabindranath Tagore",
      "C.V. Raman",
      "Hargobind Khorana",
      "Amartya Sen",
      0,
    ],
    [
      "Who is known as the 'Nightingle of India'?",
      "Lata Mangeshkar",
      "Asha Bhosle",
      "Sarojini Naidu",
      "M.S. Subbulakshmi",
      2,
    ],
  ];

  let geographyQuestions = [
    [
      "Which country is known as the 'Land of the Rising Sun'?",
      "China",
      "Japan",
      "South Korea",
      "Thailand",
      1,
    ],
    [
      "Which river is the longest in the world?",
      "Nile",
      "Amazon",
      "Mississippi",
      "Yangtze",
      0,
    ],
    [
      "Which mountain range is the longest in the world?",
      "Andes",
      "Rocky Mountains",
      "Himalayas",
      "Alps",
      0,
    ],
    [
      "Which ocean is the largest?",
      "Pacific Ocean",
      "Atlantic Ocean",
      "Indian Ocean",
      "Arctic Ocean",
      0,
    ],
    [
      "Which country is known as the 'Land of Fire and Ice'?",
      "Norway",
      "Iceland",
      "Greenland",
      "Sweden",
      1,
    ],
    [
      "What is the tallest mountain in the world?",
      "Mount Everest",
      "K2",
      "Kangchenjunga",
      "Makalu",
      0,
    ],
    [
      "Which country is home to the Great Barrier Reef?",
      "Australia",
      "Indonesia",
      "Maldives",
      "Philippines",
      0,
    ],
    [
      "What is the largest island in the world?",
      "Greenland",
      "Madagascar",
      "Borneo",
      "New Guinea",
      0,
    ],
    [
      "Which continent is the driest in the world?",
      "Africa",
      "Australia",
      "Asia",
      "South America",
      1,
    ],
    [
      "Which country is known as the 'Land of a Thousand Lakes'?",
      "Finland",
      "Canada",
      "Sweden",
      "Norway",
      0,
    ],
    [
      "Which country is known as the 'Land of Smiles'?",
      "Thailand",
      "Brazil",
      "Italy",
      "India",
      0,
    ],
    [
      "What is the largest lake in Africa?",
      "Lake Victoria",
      "Lake Tanganyika",
      "Lake Malawi",
      "Lake Turkana",
      0,
    ],
    [
      "Which continent is the largest by land area?",
      "Asia",
      "Africa",
      "North America",
      "South America",
      0,
    ],
    [
      "Which country is known as the 'Land of the Rising Sun'?",
      "China",
      "Japan",
      "South Korea",
      "Vietnam",
      1,
    ],
    [
      "Which is the longest river in the world?",
      "Nile River",
      "Amazon River",
      "Yangtze River",
      "Mississippi River",
      0,
    ],
    [
      "Which country is known as the 'Land Down Under'?",
      "Australia",
      "New Zealand",
      "Canada",
      "South Africa",
      0,
    ],
    [
      "Which city is located at the confluence of the Danube and Sava rivers?",
      "Budapest",
      "Vienna",
      "Prague",
      "Belgrade",
      3,
    ],
    [
      "What is the largest country in South America?",
      "Brazil",
      "Argentina",
      "Colombia",
      "Peru",
      0,
    ],
    [
      "Which strait separates Asia and North America?",
      "Strait of Gibraltar",
      "Strait of Hormuz",
      "Strait of Malacca",
      "Bering Strait",
      3,
    ],
    [
      "Which country is known for its fjords?",
      "Norway",
      "Sweden",
      "Finland",
      "Denmark",
      0,
    ],
    [
      "Which city is located on the banks of the Nile River?",
      "Cairo",
      "Rome",
      "Athens",
      "Paris",
      0,
    ],
    [
      "Which country is the largest producer of coffee?",
      "Brazil",
      "Colombia",
      "Vietnam",
      "Ethiopia",
      0,
    ],
    [
      "Which country is the smallest in terms of land area?",
      "Monaco",
      "Maldives",
      "San Marino",
      "Nauru",
      2,
    ],
    [
      "What is the largest coral reef system in the world?",
      "Great Barrier Reef",
      "Mesoamerican Barrier Reef",
      "Andros Barrier Reef",
      "Red Sea Coral Reef",
      0,
    ],
    [
      "Which country is known as the 'Land of Fire and Ice'?",
      "Greenland",
      "Iceland",
      "Finland",
      "Sweden",
      1,
    ],
    [
      "Which city is located at the mouth of the Amazon River?",
      "Lima",
      "Buenos Aires",
      "Rio de Janeiro",
      "Belem",
      3,
    ],
    [
      "What is the capital of India?",
      "New Delhi",
      "Mumbai",
      "Kolkata",
      "Chennai",
      0,
    ],
    [
      "Which is the highest mountain peak in India?",
      "Kangchenjunga",
      "Mount Everest",
      "Nanda Devi",
      "Kamet",
      0,
    ],
    [
      "Which is the longest river in India?",
      "Ganges",
      "Yamuna",
      "Brahmaputra",
      "Godavari",
      0,
    ],
    [
      "Which is the largest state in India by area?",
      "Rajasthan",
      "Madhya Pradesh",
      "Maharashtra",
      "Uttar Pradesh",
      0,
    ],
    [
      "Which is the southernmost point of the Indian mainland?",
      "Cape Comorin",
      "Rameswaram",
      "Kanyakumari",
      "Trivandrum",
      2,
    ],
    [
      "Which city is known as the 'Pink City' of India?",
      "Jaipur",
      "Jaisalmer",
      "Udaipur",
      "Agra",
      0,
    ],
    [
      "Which is the largest freshwater lake in India?",
      "Dal Lake",
      "Vembanad Lake",
      "Wular Lake",
      "Chilika Lake",
      2,
    ],
    [
      "Which state in India is known as the 'Land of Five Rivers'?",
      "Punjab",
      "Haryana",
      "Uttar Pradesh",
      "Gujarat",
      0,
    ],
    [
      "Which is the wettest place in India?",
      "Mawsynram",
      "Cherrapunji",
      "Agumbe",
      "Dibrugarh",
      0,
    ],
    [
      "Which is the largest city in India by population?",
      "Mumbai",
      "Delhi",
      "Kolkata",
      "Chennai",
      0,
    ],
    [
      "Which is the largest saltwater lake in India?",
      "Chilika Lake",
      "Dal Lake",
      "Sambhar Lake",
      "Vembanad Lake",
      2,
    ],
    [
      "Which state in India is known as the 'Land of the Gods'?",
      "Uttarakhand",
      "Himachal Pradesh",
      "Jammu and Kashmir",
      "Sikkim",
      0,
    ],
    [
      "Which is the largest tiger reserve in India?",
      "Kaziranga National Park",
      "Sunderbans National Park",
      "Bandhavgarh National Park",
      "Jim Corbett National Park",
      3,
    ],
    [
      "Which is the largest delta in India?",
      "Ganga-Brahmaputra Delta",
      "Krishna Delta",
      "Godavari Delta",
      "Kaveri Delta",
      0,
    ],
    [
      "Which state in India is known as the 'Spice Garden of India'?",
      "Kerala",
      "Karnataka",
      "Tamil Nadu",
      "Andhra Pradesh",
      0,
    ],
    [
      "Which city is known as the 'Manchester of South India'?",
      "Coimbatore",
      "Kochi",
      "Mysore",
      "Hyderabad",
      0,
    ],
    [
      "Which is the largest cave temple in India?",
      "Kailasa Temple",
      "Ellora Caves",
      "Ajanta Caves",
      "Amarnath Cave",
      1,
    ],
    [
      "Which state in India is known as the 'Land of Festivals'?",
      "Rajasthan",
      "Gujarat",
      "Maharashtra",
      "West Bengal",
      3,
    ],
    [
      "Which is the driest place in India?",
      "Jaisalmer",
      "Leh",
      "Bikaner",
      "Kutch",
      1,
    ],
    [
      "Which state in India is known as the 'Land of Backwaters'?",
      "Kerala",
      "Tamil Nadu",
      "Karnataka",
      "Andhra Pradesh",
      0,
    ],
    [
      "Which is the largest mangrove forest in India?",
      "Sundarbans",
      "Bhitarkanika",
      "Pichavaram",
      "Mangrove National Park",
      0,
    ],
    [
      "Which city is located on the banks of the Brahmaputra River?",
      "Guwahati",
      "Dibrugarh",
      "Silchar",
      "Tezpur",
      0,
    ],
    [
      "Which state in India is known as the 'Land of Lakes'?",
      "Madhya Pradesh",
      "Rajasthan",
      "Gujarat",
      "Maharashtra",
      1,
    ],
    [
      "Which is the largest coral reef system in India?",
      "Gulf of Mannar",
      "Lakshadweep Coral Reef",
      "Andaman and Nicobar Coral Reef",
      "Netrani Island",
      2,
    ],
    [
      "Which city is known as the 'City of Lakes'?",
      "Udaipur",
      "Jaipur",
      "Jaisalmer",
      "Pushkar",
      0,
    ],
    [
      "Which is the highest waterfall in India?",
      "Dudhsagar Falls",
      "Jog Falls",
      "Barkana Falls",
      "Kunchikal Falls",
      1,
    ],
    [
      "Which state in India is known as the 'Land of Forests'?",
      "Assam",
      "Madhya Pradesh",
      "Uttarakhand",
      "Arunachal Pradesh",
      3,
    ],
    [
      "Which is the only floating national park in India?",
      "Kaziranga National Park",
      "Hemis National Park",
      "Keibul Lamjao National Park",
      "Ranthambore National Park",
      2,
    ],
    [
      "Which state in India is known as the 'Land of Rivers'?",
      "Uttar Pradesh",
      "Bihar",
      "West Bengal",
      "Maharashtra",
      1,
    ],
  ];

  let mathLogicQuestions = [
    ["What is the square root of 64?", "4", "8", "6", "10", 1],
    ["Simplify the expression: 3 * (4 + 2) - 8 / 2", "16", "20", "18", "14", 2],
    [
      "What is the value of pi (π) to two decimal places?",
      "3.12",
      "3.14",
      "3.16",
      "3.10",
      1,
    ],
    ["Solve the equation for x: 2x + 5 = 17", "6", "8", "7", "9", 2],
    [
      "What is the next number in the sequence: 1, 4, 9, 16, __",
      "25",
      "26",
      "27",
      "32",
      0,
    ],
    [
      "If a triangle has angles measuring 30 degrees, 60 degrees, and 90 degrees, what type of triangle is it?",
      "Equilateral triangle",
      "Isosceles triangle",
      "Scalene triangle",
      "Right triangle",
      3,
    ],
    ["What is the value of 5! (factorial)?", "120", "60", "240", "720", 3],
    ["Solve for x: 2x - 5 = 3x + 4", "-9", "9", "6", "14", 0],
    [
      "If a = 4 and b = 7, what is the value of a^2 + b^2?",
      "41",
      "65",
      "57",
      "45",
      2,
    ],
    [
      "What is the sum of the interior angles of a triangle?",
      "90 degrees",
      "180 degrees",
      "270 degrees",
      "360 degrees",
      1,
    ],
    ["How many sides does a heptagon have?", "5", "6", "7", "8", 2],
    [
      "Simplify the expression: 3x + 2y - 5x + 4y",
      "-2x + 6y",
      "-2x - 2y",
      "2x + 6y",
      "2x - 2y",
      1,
    ],
    [
      "If a train travels at a speed of 60 miles per hour, how far will it travel in 3 hours?",
      "90 miles",
      "120 miles",
      "150 miles",
      "180 miles",
      3,
    ],
    ["What is the value of log base 10 of 100?", "1", "10", "100", "2", 2],
    ["If 2x + 3 = 9, what is the value of x?", "2", "3", "4", "5", 1],
  
    // Math Questions (20)
    ["What is the value of e ?", "3.142", "2.653", "2.718", "2.879", 2],
    ["Solve the equation: 2x + 5 = 15", "x = 5", "x = 6", "x = 7", "x = 8", 1],
    ["What is the square root of 256?", "14", "16", "18", "12", 1],
    ["What is 12 multiplied by 9?", "92", "108", "106", "118", 1],
    ["Simplify: 4(2 + 5) - 3(1 + 2)", "25", "14", "12", "9", 3],
    [
      "What is the next number in the sequence: 1, 1, 2, 3, 5, 8, ...",
      "13",
      "14",
      "15",
      "16",
      0,
    ],
    [
      "What is the value of 7! (7 factorial)?",
      "5040",
      "40320",
      "362880",
      "518400",
      1,
    ],
    ["Solve the equation: 3x - 7 = 20", "x = 7", "x = 9", "x = 10", "x = 11", 2],
    [
      "What is the sum of angles in a kite?",
      "90 degrees",
      "180 degrees",
      "270 degrees",
      "360 degrees",
      3,
    ],
    [
      "If a circle has a diameter of 10, what is its radius?",
      "5",
      "10",
      "15",
      "20",
      0,
    ],
    [
      "John's father is twice as old as John. If John is 10 years old, how old is his father?",
      "10 years old",
      "20 years old",
      "30 years old",
      "40 years old",
      1,
    ],
    [
      "If a plane crashes on the border between the US and Canada, where would the survivors be buried?",
      "US",
      "Canada",
      "Neither",
      "Both",
      3,
    ],
    [
      "A farmer has 17 cows. All but 9 die. How many cows are left?",
      "9",
      "8",
      "7",
      "None",
      0,
    ],
    ["How many months have 28 days?", "1", "6", "12", "All", 3],
    [
      "How many legs does a dog have if you call its tail a leg?",
      "3",
      "4",
      "5",
      "None",
      1,
    ],
    [
      "Mary's father has 5 daughters: Nana, Nene, Nini, Nono, and ???",
      "Mama",
      "Mary",
      "Moni",
      "Meme",
      1,
    ],
    [
      "If there are 12 fish and half of them drown, how many are left?",
      "6",
      "3",
      "0",
      "12",
      3,
    ],
    [
      "If you had only one match and entered a dark room containing an oil lamp, some kindling wood, and a newspaper, which would you light first?",
      "Match",
      "Oil lamp",
      "Kindling wood",
      "Newspaper",
      0,
    ],
    [
      "A plane crashes on the border of the US and Canada. Where would the survivors be buried?",
      "US",
      "Canada",
      "Neither",
      "Both",
      2,
    ],
    ["How many sides does a circle have?", "0", "1", "2", "Infinite", 1],
  ];

  let scienceTechQuestions = [
    ["What is the chemical symbol for gold?", "Au", "Ag", "Pt", "Go", 0],
    [
      "What is the SI unit of electric current?",
      "Volt",
      "Ampere",
      "Ohm",
      "Watt",
      1,
    ],
    [
      "What is the process by which plants convert sunlight into energy called?",
      "Photosynthesis",
      "Respiration",
      "Fermentation",
      "Transpiration",
      0,
    ],
    [
      "Which particle has a positive charge?",
      "Proton",
      "Neutron",
      "Electron",
      "Photon",
      0,
    ],
    [
      "Who is known as the 'Father of Computer Science'?",
      "Alan Turing",
      "Bill Gates",
      "Steve Jobs",
      "Charles Babbage",
      3,
    ],
    [
      "What is the largest planet in our solar system?",
      "Mercury",
      "Venus",
      "Jupiter",
      "Mars",
      2,
    ],
    [
      "What is the unit of measurement for force?",
      "Newton",
      "Watt",
      "Joule",
      "Pascal",
      0,
    ],
    [
      "What is the process of a solid changing directly into a gas called?",
      "Sublimation",
      "Evaporation",
      "Condensation",
      "Fusion",
      0,
    ],
    [
      "What is the branch of science that studies the Earth's atmosphere?",
      "Biology",
      "Chemistry",
      "Geology",
      "Meteorology",
      3,
    ],
    [
      "What is the unit of measurement for frequency?",
      "Hertz",
      "Watt",
      "Ampere",
      "Ohm",
      0,
    ],
    [
      "Which scientist developed the theory of general relativity?",
      "Isaac Newton",
      "Marie Curie",
      "Albert Einstein",
      "Galileo Galilei",
      2,
    ],
    [
      "What is the SI unit of temperature?",
      "Kelvin",
      "Celsius",
      "Fahrenheit",
      "Rankine",
      0,
    ],
    [
      "What is the process of breaking down complex substances into simpler ones called?",
      "Oxidation",
      "Hydration",
      "Combustion",
      "Decomposition",
      3,
    ],
    [
      "What is the study of heredity and variation in organisms called?",
      "Genetics",
      "Ecology",
      "Botany",
      "Zoology",
      0,
    ],
    [
      "What is the unit of measurement for electrical resistance?",
      "Volt",
      "Ampere",
      "Ohm",
      "Watt",
      2,
    ],
    [
      "Which gas makes up the majority of the Earth's atmosphere?",
      "Nitrogen",
      "Oxygen",
      "Carbon dioxide",
      "Argon",
      0,
    ],
    [
      "Who is credited with discovering the structure of DNA?",
      "Francis Crick",
      "Rosalind Franklin",
      "James Watson",
      "Gregor Mendel",
      1,
    ],
    [
      "What is the process of converting a liquid into a solid called?",
      "Evaporation",
      "Condensation",
      "Freezing",
      "Sublimation",
      2,
    ],
    [
      "What is the unit of measurement for energy?",
      "Joule",
      "Watt",
      "Ampere",
      "Volt",
      0,
    ],
    [
      "Which element has the atomic number 6?",
      "Oxygen",
      "Carbon",
      "Hydrogen",
      "Nitrogen",
      1,
    ],
    ["What is the SI unit of pressure?", "Pascal", "Newton", "Joule", "Watt", 0],
    [
      "What is the process of converting a gas into a liquid called?",
      "Evaporation",
      "Condensation",
      "Sublimation",
      "Vaporization",
      1,
    ],
    [
      "What is the study of the Earth's physical structure, history, and the processes that shape it called?",
      "Biology",
      "Chemistry",
      "Geology",
      "Physics",
      2,
    ],
    [
      "Which planet is known as the 'Blue Planet'?",
      "Mars",
      "Jupiter",
      "Earth",
      "Neptune",
      2,
    ],
    [
      "What is the unit of measurement for electric potential difference?",
      "Volt",
      "Ampere",
      "Ohm",
      "Watt",
      0,
    ],
    [
      "What is the process of combining hydrogen atoms to form helium called?",
      "Fusion",
      "Fission",
      "Combustion",
      "Ionization",
      0,
    ],
    [
      "Which branch of science deals with the study of sound and its properties?",
      "Biology",
      "Chemistry",
      "Geology",
      "Acoustics",
      3,
    ],
    [
      "What is the chemical formula for table salt?",
      "NaCl",
      "H2O",
      "CO2",
      "CH4",
      0,
    ],
    [
      "Who is credited with inventing the telephone?",
      "Thomas Edison",
      "Nikola Tesla",
      "Alexander Graham Bell",
      "Benjamin Franklin",
      2,
    ],
    [
      "What is the branch of biology that deals with the study of plants?",
      "Botany",
      "Zoology",
      "Genetics",
      "Ecology",
      0,
    ],
    [
      "What is the unit of measurement for electric power?",
      "Joule",
      "Watt",
      "Ampere",
      "Volt",
      1,
    ],
    [
      "Which gas is responsible for the ozone layer depletion?",
      "Carbon dioxide",
      "Nitrogen",
      "Oxygen",
      "Chlorofluorocarbons (CFCs)",
      3,
    ],
    [
      "What is the process of converting light energy into electrical energy called?",
      "Reflection",
      "Refraction",
      "Photosynthesis",
      "Solar energy conversion",
      3,
    ],
    [
      "Which scientist is known for the laws of motion?",
      "Isaac Newton",
      "Marie Curie",
      "Albert Einstein",
      "Galileo Galilei",
      0,
    ],
    [
      "What is the study of the behavior and interaction of matter and energy called?",
      "Physics",
      "Chemistry",
      "Biology",
      "Geology",
      0,
    ],
    [
      "What is the largest moon in our solar system?",
      "Europa",
      "Titan",
      "Ganymede",
      "Callisto",
      2,
    ],
    [
      "What is the unit of measurement for electric resistance?",
      "Ohm",
      "Ampere",
      "Watt",
      "Volt",
      0,
    ],
    [
      "Which scientist proposed the theory of general relativity?",
      "Isaac Newton",
      "Marie Curie",
      "Albert Einstein",
      "Galileo Galilei",
      2,
    ],
    [
      "What is the process of converting electrical energy into mechanical energy called?",
      "Transformation",
      "Transduction",
      "Transcription",
      "Electromechanical conversion",
      3,
    ],
    [
      "Which element is essential for all organic compounds?",
      "Oxygen",
      "Carbon",
      "Hydrogen",
      "Nitrogen",
      1,
    ],
  ];